import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import { createClient } from '@/lib/supabase-server'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { scenarioId, email } = await req.json()

  const { data: scenario } = await supabase
    .from('scenarios')
    .select('title, category, scenario_text, action_items(*)')
    .eq('id', scenarioId)
    .eq('user_id', user.id)
    .single()

  if (!scenario) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const actionItemsHtml = (scenario.action_items as { title: string; timeline: string; priority: string }[])
    .map(item => `<li><strong>${item.title}</strong> – ${item.timeline} (${item.priority} priority)</li>`)
    .join('')

  await resend.emails.send({
    from: process.env.RESEND_FROM_EMAIL!,
    to: email,
    subject: `Your Future Vision: ${scenario.title}`,
    html: `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #1e293b;">
        <h1 style="color: #4f46e5;">${scenario.title}</h1>
        <p style="color: #64748b; font-size: 14px;">${scenario.category} · Future Vision</p>

        <h2>Your Future Scenario</h2>
        <div style="background: #f8fafc; border-radius: 8px; padding: 20px; font-size: 15px; line-height: 1.7;">
          ${scenario.scenario_text.replace(/\n/g, '<br>')}
        </div>

        <h2>Action Plan</h2>
        <ul style="line-height: 2;">
          ${actionItemsHtml}
        </ul>

        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 30px 0;">
        <p style="font-size: 13px; color: #94a3b8;">
          Generated by <a href="${process.env.NEXT_PUBLIC_APP_URL}" style="color: #4f46e5;">Future Vision</a>
        </p>
      </div>
    `,
  })

  return NextResponse.json({ ok: true })
}
